on:
  workflow_dispatch:
  push:
jobs:
  sync-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Switch to Python2
        run: |
          sudo apt -y install python
          sudo rm -rf /usr/bin/python
          sudo ln -s /usr/bin/python2 /usr/bin/python
          # sudo ln -s /usr/bin/python3 /usr/bin/python3
        continue-on-error: true
      - name: Make the script file executable
        run: chmod +x sync-build.sh
      - name: Run the script
        run: |
          ./sync-build.sh
