on:
  workflow_dispatch:
  push:
jobs:
  sync-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Install Deps
        run: |
          sudo apt update
          sudo apt install python3 ccache -y
          curl -o libcloog-isl-dev_0.17.0-1_amd64.deb  http://security.ubuntu.com/ubuntu/pool/universe/c/cloog/libcloog-isl-dev_0.17.0-1_amd64.deb 
          sudo dpkg -i libcloog-isl-dev_0.17.0-1_amd64.deb 
      - name: Switch to Python2
        run: |
          sudo apt -y install python2
          sudo rm -rf /usr/bin/python
          sudo ln -s /usr/bin/python2 /usr/bin/python
          # sudo ln -s /usr/bin/python3 /usr/bin/python3
        continue-on-error: true
      - name: Make the script file executable
        run: chmod +x sync-build.sh
      - name: Run the script
        run: |
          ./sync-build.sh
